##
## Kong docker-compose for fast installation
##
version: "3.7"

networks:
 keycloak-net:
  name: keycloak-net
  driver: bridge
  ipam:
    config:
      - subnet: 172.1.3.0/24

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    command: "start-dev"
    restart: unless-stopped
    networks:
      - keycloak-net
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    networks:
      - keycloak-net
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
  